title: Simon Yin
description: 个人主页与博客
url: https://Simon96128.github.io
lang: zh-CN
github_username: Simon96128
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .bundle
